# 应用程序信息
name: sudoku  #应用程序的名称
description: "数独"  #应用程序的描述
publish_to: 'none'  # 以下行防止将包意外发布到 pub.dev，建议私有包保留此设置，如果希望发布到 pub.dev 请移除本行
version: 1.0.5+20260328 #应用程序的版本号和构建号，版本号格式为三个用点分隔的数字，如 1.2.43，后面可以跟一个用+号分隔的可选构建号

# 应用程序名称
flutter_app_name:
  name: "数独"

# 应用程序的环境要求，指定 Dart SDK 版本
environment:
  sdk: ^3.11.4

# 依赖项指定，要自动升级依赖到最新版本，可运行 `flutter pub upgrade --major-versions，也可以手动更新下方版本号为 pub.dev 上的最新版本
# 要查看可用新版本，运行 `flutter pub outdated`
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:  # 国际化支持
    sdk: flutter

  # UI 与核心功能
  intl: ^0.20.2 # 国际化支持，用于处理日期、时间、数字和货币等本地化格式
  cupertino_icons: ^1.0.9 # Cupertino 图标字体，用于 iOS 风格图标，与 CupertinoIcons 类配合使用
  provider: ^6.1.5+1  # 状态管理库，用于在应用程序中共享和管理状态
  shared_preferences: ^2.5.5 # 用于在应用程序中存储和检索简单键值对数据
  path_provider: ^2.1.5  # 用于在应用程序中获取常用路径，如文档目录、缓存目录等
  flutter_svg: ^2.2.4  # 用于加载和显示 SVG 图片
  logger: ^2.7.0  # 日志库，用于记录应用程序运行时的信息、错误和调试消息
  collection: ^1.18.0  # 集合操作库，提供了一组用于操作集合的扩展方法和函数
  vector_math: ^2.2.0  # 向量数学库，用于处理 2D 和 3D 向量运算
  # 音频
  audioplayers: ^6.6.0
  # 用于获取应用版本信息
  package_info_plus: ^9.0.0
  meta: ^1.17.0

# 开发依赖项
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  fake_async: ^1.0.0
  flutter_lints: ^6.0.0       # 代码规范检查（开发依赖）
  flutter_launcher_icons: ^0.14.4  # 应用图标生成工具
  test: ^1.30.0

# Flutter专用配置
flutter:
  generate: true  # 启用 Flutter 代码生成，如生成路由、主题等
  uses-material-design: true  # 启用 Material Design 图标字体，用于使用 Material Icons 类中的图标
  # 应用程序使用的资源文件列表
  assets:
    - assets/images/sudoku.svg
    - assets/images/sudoku.png
    - assets/music/background.mp3
    - assets/music/start_sound.mp3
    - assets/music/complete_sound.mp3
    # 核心模板文件
    - assets/templates/

# 应用图标生成配置,与 flutter_launcher_icons 包配合使用
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#FFFFFF" # 可选：Android自适应图标背景色
